#this file perform unique partition on genes across 12 traits
#to avoid using the same gene multiple times for different traits


library(caret)
#the path saving the results of MakeFeatures.r
path.work <- "data/02_features/"

#the files generated by MakeFeatures.r
traits.files <- list.files(path.work)

#############################
all.train.genes <- NULL
disease.id <- NULL
for(test.trait in traits.files ){
  load( paste0( path.work, test.trait),verbose=TRUE)
  print(dim(locus.collapse))
  locus.collapse <- data.frame(locus.collapse)
  locus.collapse$gene.names <- rownames(locus.collapse)
  all.train.genes <- rbind(all.train.genes, locus.collapse )
  disease.id <- c(disease.id,rep( match(test.trait,traits.files) ,nrow(locus.collapse)))
}

all.genes <- all.train.genes
all.genes$GWAS <- disease.id
table(all.genes$GWAS, all.genes$PC.gene)

#now remove the AMP gene entries from all other traits because we want to reserve
#them for T2D 
omim_genes <- read.table("src/03_make-features/positive-control-omim-genes-hdo-latest.txt",header=TRUE)
drug_genes <- read.table("src/03_make-features/positive-control-drug-targets-knownaction-latest.txt",header=TRUE)
amp_genes <- read.table("src/03_make-features/positive-control-t2d-amp-latest.txt",header=TRUE)

#exclude t2d
genes.exc.t2d <- all.genes[ -which(all.genes$GWAS==grep("t2d", traits.files)),]
#exclude AMP genes  
genes.exc.t2d <- genes.exc.t2d[-which(genes.exc.t2d$gene.names %in% amp_genes$Gene.Symbol),]

#consolidated genes, kept AMP genes only for T2D 
new.all.genes <- rbind(genes.exc.t2d, all.genes[which(all.genes$GWAS==grep("t2d", traits.files)),])

#####################################################################################
#####################################################################################
#no perform partition to make sure each gene only appears once in either training or test
source("src/04_train-models/part_func.r")

total.genes   <- partition_genes(new.all.genes$gene.names,  new.all.genes, new.all.genes$PC.gene  )

#the file containing all PC-locus genes from 12 traits
#each gene only appears once
new.new.all.genes <- total.genes$uniq.x

rownames(new.new.all.genes) <- total.genes$uniq.names

save(new.new.all.genes, file="data/03_partitioned-gene-sets/GenPartitionLocus.RData")
